#!/usr/bin/env bash
#Install a new Nginx server server and configure it so that its HTTP response contains a custom header
#Name of the custom HTTP heade must be X-Servd-By
#Value of the custom HTTP header must be the hostname of the server Nginx is running on

#Update the package list
apt-get update

#Install Nginx
apt-get -y install nginx

#configure Nginx to add a custom header
sed -i '/server_name_;/a\\tadd_header X-Served-By "$HOSTNAME";' /etc//nginx/sites-available/default

#Start Nginx Service
sudo service nginx start
